# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Aleph.js in Deno

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }} # runs a test on macOS, Windows and Ubuntu

    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

       - name: Setup wasm-pack
         uses: jetli/wasm-pack-action@v0.3.0
         with:
          version: latest

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Cache std modules
        run: deno cache std.ts

      - name: Run deno tests
        run: deno test -A --unstable

      - name: Run swc tests
        run: cd swc && cargo test --all
